---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: nexgen-azure-keyvault-store
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  provider:
    azurekv:
      authType: ManagedIdentity
      environmentType: PublicCloud
      identityId: 'd79d871a-f94e-4c44-bd6e-81661c75af1a'
      tenantId: 'a1796f17-15cf-4938-bfcf-f9fc092b2638'
      vaultUrl: https://kv-nexgen-infrajet.vault.azure.net
  retrySettings:
    maxRetries: 5
    retryInterval: 10s
