---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: tls-certificate
spec:
  namespaceSelector:
    matchLabels:
      type: environment
  refreshTime: 2m
  externalSecretSpec:
    data:
    - remoteRef:
        key:  infrajet-development-env-cert17533cd9-ffa2-4a55-a2cb-e1b73d0ed717
      secretKey: certificate
    refreshInterval: 1h
    secretStoreRef:
      kind: ClusterSecretStore
      name: nexgen-azure-keyvault-cert-store
    target:
      name: tls-certificate
      template:
        engineVersion: v2
        data:
          tls.crt: "{{`{{ .certificate | b64dec | pkcs12cert }}`}}"
          tls.key: "{{`{{ .certificate | b64dec | pkcs12key }}`}}"
