---
{{ $environment := printf "%s" .Values.global.environment -}}
{{- $fullAppName := printf "%s-%s" .Values.appName $environment -}}

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ printf "secret-%s" $fullAppName }}
  labels:
    app: {{ printf "%s" .Values.appName }}
    environment: {{ $environment }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: nexgen-azure-keyvault-store
  dataFrom:
    - extract:
        key: {{ $fullAppName }}
