---
apiVersion: v2
name: infra-ingress-nginx
description: Install NGINX Ingress Controller.

maintainers:
  - name: darshanasys
    email: darshana.m@ngtl.tech

type: application
version: 0.1.4

dependencies:
  - name: ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx
    version: 4.13.3
